### ISSUE TITLE
Clarification of "Universal"

### ISSUE THREAD

**Issue by BradKML** [TigerHix/shimeji-universal#4]
As addressed in https://github.com/gil/shimeji-ee/issues/1 it might be good to mention other platforms, and define the "Universal" part addresses these three platforms.
- Windows https://github.com/gil/shimeji-ee
- Mac https://github.com/nonowarn/shimeji4mac
- Linux https://github.com/asdfman/linux-shimeji

**Comment by TigerHix** [comment]
Updated README.md to clarify this is for Windows, but I don't think mentioning other platforms is necessary. Also, the shimeji-ee repository you linked to also has builds for Linux and Mac.

**Comment by BradKML** [comment]
@TigerHix the EE repo is still doing experimental support for Linux and Mac ATM (I think).
